from django.conf import settings

DEFAULT_SERIALIZATION_PLUGINS = tuple()
DEFAULT_SKIP = tuple()
DEFAULT_GROUPING = {}
DEFAULT_PREFIXES = tuple()
DEFAULT_PREFIX_SEPARATOR = '_'

TO_DICT_SERIALIZATION_PLUGINS = settings.TO_DICT_SERIALIZATION_PLUGINS or DEFAULT_SERIALIZATION_PLUGINS
TO_DICT_SKIP = settings.TO_DICT_SKIP or DEFAULT_SKIP
TO_DICT_GROUPING = settings.TO_DICT_GROUPING or DEFAULT_GROUPING
TO_DICT_PREFIXES = settings.TO_DICT_PREFIXES or DEFAULT_PREFIXES
TO_DICT_PREFIX_SEPARATOR = settings.TO_DICT_PREFIX_SEPARATOR or DEFAULT_PREFIX_SEPARATOR